Increase test code coverage
yiisoft/log-target-file pull request #7
Opened 2020-07-09 19:37 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

2020-07-09 21:33 UTC, hiqsol approved these changes

2020-07-10 15:10 UTC, samdark requested changes

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +        $logger->debug("\0");
Why null-byte instead of another `x`? Any special meaning here?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +        $logger->debug(str_repeat('x', 1024));
```suggestion
        $oneKilobyteOfData = str_repeat('x', 1024);
        $logger->debug($oneKilobyteOfData);
```

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +            $logger->debug(str_repeat('x', 1024));
```suggestion
            $oneKilobyteOfData = str_repeat('x', 1024);
            $logger->debug($oneKilobyteOfData);
```

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +        foreach (range(1, $filesCount+2) as $i) {
`while` may be a bit easier to read in this case...

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +     * @dataProvider filesCountProvider()
Do we need different number of files? Does coverage change if we always use 3?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +        foreach (range(1, $filesCount) as $counter) {
`while` may be a bit easier to read in this case...

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +        // check that next file is not exist
```suggestion
        // check that next file does not exist
```

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +     * @dataProvider filesSizesProvider()
Do we need all these sizes? Maybe one size is enough?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +    public function testMaxFileSizeLowerThanOne(): void
How about throwing an exception in this case instead?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +    public function testSetMaxFileSizeLowerThanOne(): void
How about throwing an exception in this case instead?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +    public function testMaxFilesLowerThanOne(): void
How about throwing an exception in this case instead?

2020-07-10 15:10 UTC, samdark commented on tests/FileRotatorTest.php
> +    public function testSetMaxFilesLowerThanOne(): void
How about throwing an exception in this case instead?

2020-07-10 16:03 UTC, roxblnfk approved these changes

2020-07-11 20:19 UTC, merged

2020-07-11 20:19 UTC, samdark commented
👍